### ISSUE TITLE
Add CLI pagination documentation

### ISSUE THREAD

**Issue by wass3r** [go-vela/docs-old#105]
## Description

_What is your idea?_

Add information on how to paginate through multi-page results with the CLI

## Value

_Why is this important? Who does it impact? Will this make something better, faster, etc?_

To let users know that there's a way to get to further results

## Definition of Done

_What is the end goal of this story?_

Information about the pagination parameters is added to the docs

## Effort  (Optional)

_Estimated effort to complete this story? (Best Guess e.g. 1-2 days)_

1 day

## Impacted Personas (Optional)

_Which personas will benefit from completing this story? (Users, Administrators, etc)_

Users

**Comment by jbrockopp** [comment]
Hello 👋 

The Vela admins have decided to condense all existing issues into a single repo found @ [go-vela/community](https://github.com/go-vela/community).

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
