### ISSUE TITLE
Secret doco missing --page and --per-page

### ISSUE THREAD

**Issue by galacticgumshoe** [go-vela/docs-old#119]
I had noticed that older secrets were no longer appearing on my list when doing `vela get secret --org data-engineering-fieldops --type org --repo '*'`. After posting this to #vela on Slack, I came to learn about two flags which are not documented. These do allow me to view secrets beyond my initial page, so should be added to the documentation https://go-vela.github.io/docs/cli/secret/:

> --page
> --per-page

**Comment by wass3r** [comment]
related: https://github.com/go-vela/docs/issues/105

**Comment by jbrockopp** [comment]
Hello 👋 

The Vela admins have decided to condense all existing issues into a single repo found @ [go-vela/community](https://github.com/go-vela/community).

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
