### ISSUE TITLE
Install - Please Don't Place Exe's In C:\Windows\System32

### ISSUE THREAD

**Issue by mikebeckel** [go-vela/docs-old#131]
Please don't place EXE's in C:\Windows\System32. It's a OS folder and while it makes it easy to make your executable accessible as it's included in the System Path it's not the correct approach for several reasons. 

* It obfuscates the origin of your executable and can be interpreted as malware. 
* It requires that users have Administrative rights to modify

The best approach is to create an installer so that it can be installed to Program Files. The next best approach is for the user to place in into a directory of their choosing, such as their user profile, and update the User Path so that it's accessible from anywhere for that user.

**Comment by wass3r** [comment]
Thanks for the feedback. Is NSIS still the go-to for creating installers? Or do you have any recommendations?

**Comment by kneal** [comment]
@mikebeckel Do you know how common chocolatey is for windows users?
https://chocolatey.org/

We could potentially look into adding it there as well if that's generally seen as best practice.

**Comment by mikebeckel** [comment]
NSIS or WIX are pretty common these days. Chocolatey usage is definitely picking up. It doesn't get around the admin rights issues of regular software install, however if the Vela CLI was installed into a user directory and the the user path updated then I could see this as a pretty viable solution.

**Comment by jbrockopp** [comment]
Hello 👋 

The Vela admins have decided to condense all existing issues into a single repo found @ [go-vela/community](https://github.com/go-vela/community).

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
