### ISSUE TITLE
Explain where to get token

### ISSUE THREAD

**Issue by wass3r** [go-vela/docs-old#135]
Consider enumerating the different methods to retrieve the token to use in API calls and add them to: https://go-vela.github.io/docs/api/authentication/

**Comment by jbrockopp** [comment]
Hello 👋 

The Vela admins have decided to condense all existing issues into a single repo found @ [go-vela/community](https://github.com/go-vela/community).

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
