### ISSUE TITLE
Authentication - Configuration File - Incorrect CLI Tags

### ISSUE THREAD

**Issue by jstef16** [go-vela/docs-old#161]
On https://go-vela.github.io/docs/cli/authentication/#configuration-file the docs list:
`vela login --api.addr <vela server url>` and `vela generate config --api.addr <vela server url> --api.token <personal token>` but the flags beginning with `api` do not exist, and should be:
`vela login --addr <vela server url>` and `vela generate config --addr <vela server url> --token <personal token>` 

vela version 0.4.1

**Comment by wass3r** [comment]
thanks for opening the issue. you caught us in a transition and we optimistically updated our docs ahead of time. the CLI has been upgraded to match this in the meantime. closing the issue.
