### ISSUE TITLE
Substitution

### ISSUE THREAD

**Issue by benzvan** [go-vela/docs-old#226]
Many descriptions of variable substitution are vague. It looks like the substitution follows bash 4.0 rules but is unclear. A link to bash explanations of substitutions, if valid or describing the substitutions would be greatly appreciated.

**Comment by JordanSussman** [comment]
The underlying library that implements the variable substitution has somewhat decent explanation of the available functions [here](https://github.com/drone/envsubst/blob/cbf718ac543135d7e9fd2b204376b6f9c2b9a891/readme.md).  Are you looking for some specific example(s) beyond what is offered in that link?

**Comment by benzvan** [comment]
This is where I was looking https://go-vela.github.io/docs/reference/environment/substitution/
