### ISSUE TITLE
Templates tutorial does not link to reference documentation

### ISSUE THREAD

**Issue by JohnCgp** [go-vela/docs-old#237]
When trying to read up on vela templates and how they work I ended up on the [templates section](https://go-vela.github.io/docs/templates/) and the tutorial. Upon wanting to find out more about the `source` tag I couldn't find any relevant information; I think it would be handy to link to the reference documentation from the tutorial root to make it more discoverable.

![image](https://user-images.githubusercontent.com/73995615/123666386-71dd5c00-d839-11eb-9a39-28a30d67ebaf.png)

**Comment by JohnCgp** [comment]
Noticed the footer links are to child pages and not hand editable; opened a PR that links to the ref docs near the beginning of the document.

**Comment by wass3r** [comment]
closing, since the PR was merged. Thank you!
