### ISSUE TITLE
No documentation on how to install

### ISSUE THREAD

**Issue by ziakhaan** [go-vela/docs-old#313]
For installation and usage, please [visit our user docs](https://go-vela.github.io/docs).

Where is the installation info ? how will a beginner find info on how to install. 

I have spent hours on trying to figuring out the installation guide, but in the whole of website there is none.

Why was this even thought of ? If there is no installation guide what kind of expectation is needed for a beginner to find out the info ?

Or is there a service fee for it ?

**Comment by JordanSussman** [comment]
Sorry for the confusion! The installation docs are currently located on https://go-vela.github.io/docs/administration/. Would it help if we made the changes suggested on https://github.com/go-vela/docs/issues/309 to make the installation docs more discoverable?

**Comment by ziakhaan** [comment]
yes that would definitely help. I was almost lurking here and there looking for the installation info.
